# Generated by Django 4.0.3 on 2022-03-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuelgallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'Galleries'},
        ),
        migrations.AddField(
            model_name='gallery',
            name='photos',
            field=models.ImageField(default='default.png', upload_to='photos'),
        ),
    ]
